package-lock.json
src/background.js
src/components/LeftPanel.vue
src/views/Options.vue

If config file does not exist, it is created in the root directory of the built app.
Options menu can now update the game folder and the default preset. Still trying to figure out how to get elements in other Vues to update when the user applies the new configuration.

Added functionality to Options.vue and implemented config file

---

src/App.vue
src/components/Footer.vue
src/components/Marquee.vue

Add the UX for the Patreon marqee in the footer.
Note: the Patreon list is still hardcoded
I removed the need for any pseudo-elements and fixed the scrolling of the text.

Add patreon marquee

---

src/App.vue
src/components/Footer.vue
src/components/Marquee.vue

After hooking up with the backend, getting Patreons will need to be asynchronous.
This MR makes it asynchronous.

chore: make getting Patreons async

---

package.json

Adds scripts that can be used to enable debugging from an IDE

chore: add electron debug scripts

---

src/App.vue
src/assets/scss/settings/colours.scss
src/components/Footer.vue
src/components/NavBar.vue
src/components/NewsBox.vue
src/components/PatronBox.vue
src/components/TitleBar.vue
src/components/controls/Button.vue
src/components/controls/Select.vue
src/views/ConfigureENB.vue
src/views/Resources.vue

- Makes theming easier in the future
- Makes it easier for us to easily change our brand colours
- Bring UX consistency. Users can expect certain actions using colours.
- Prevents the chance the wrong colour will be used

refactor: move all css colours to variables

---

src/components/Footer.vue

fix: fix footer not showing the correct patrons

---

.stylelintrc.json
package-lock.json
package.json
src/App.vue
src/assets/scss/font-face.scss
src/assets/scss/settings/index.scss
src/assets/scss/settings/sizes.scss
src/components/NavBar.vue
src/components/NewsBox.vue
src/components/PatronBox.vue
src/components/TitleBar.vue
src/components/controls/Button.vue
src/components/controls/Select.vue
src/views/ConfigureENB.vue
src/views/Resources.vue

- Move window height and width to variables
- Use correct import path for style settings

chore: add linting for scss files

---

package-lock.json
package.json
src/App.vue
src/assets/scss/settings/colours.scss
src/assets/scss/settings/font-face.scss
src/assets/scss/settings/font.scss
src/assets/scss/settings/index.scss
src/components/Footer.vue
src/components/List.vue
src/components/NewsBox.vue
src/components/Page.vue
src/components/PageContent.vue
src/components/PatronBox.vue
src/services/Patreon.service.ts
src/services/service-container.ts
src/views/Home.vue
tsconfig.json

- Fix UI to match the design for patrons
- Integrate with the real Patreon (via ultsky.phinocio.com/api/patreon)
- Add font variables
- Add reusable Page component
- Add reusable PageContent component
- Add library for using @Prop decorator
- Add basic IoC container
- Add Patreon service

feat: add Patreon lists

---

src/App.vue
src/assets/scss/index.scss
src/assets/scss/layout.scss
src/assets/scss/settings/colours.scss
src/assets/scss/settings/font.scss
src/assets/scss/settings/index.scss
src/assets/scss/settings/sizes.scss
src/assets/scss/utility.scss
src/components/List.vue
src/components/NavBar.vue
src/components/Page.vue
src/components/PageContent.vue
src/components/Patrons.vue
src/components/TitleBar.vue
src/components/controls/Button.vue
src/components/controls/Select.vue
src/views/ConfigureENB.vue
src/views/Home.vue
src/views/Resources.vue

Add scss index file to make importing all files easier
Also:
- Add basic layout classes
- Add a few utility classes

chore: add scss index file to make importing all files easier

---

src/assets/scss/layout.scss
src/components/TitleBar.vue

_Note_
This change relies on #47. Once #47 has been merged, this branch can be rebased onto `main` and reviewed without all the other changes brought in by #47.
closes #38

feat: allow the window to be dragged with the title bar

---

src/assets/scss/settings/colours.scss
src/components/List.vue
src/components/NavBar.vue
src/components/News.vue
src/components/PageContent.vue
src/components/controls/Button.vue
src/components/controls/Select.vue
src/views/ConfigureENB.vue
src/views/Resources.vue

fix: apply consistent colours for dropdowns, menu and resourcess

---

src/assets/scss/layout.scss
src/components/ExternalLink.vue
src/components/Footer.vue
src/components/News.vue
src/components/Patrons.vue

fix: failed requests to the Patreon API will now show an error

---

src/App.vue
src/assets/scss/settings/colours.scss
src/assets/scss/utility.scss
src/components/List.vue
src/components/News.vue

style: add custom scrollbars

---

dev-app-update.yml
package-lock.json
package.json
src/App.vue
src/assets/js/errorHandler.ts
src/assets/js/ipcHandler.ts
src/assets/js/log.ts
src/assets/scss/layout.scss
src/assets/scss/settings/colours.scss
src/assets/scss/settings/sizes.scss
src/assets/scss/utility.scss
src/background.ts
src/components/AutoUpdate.vue
src/components/NavBar.vue
src/components/News.vue
src/components/PageContent.vue
src/components/controls/Button.vue
src/enums/IPCEvents.ts
src/main.ts
src/views/ConfigureENB.vue

- fix logger and print logs in development
closes #31

feat: add auto updating

---

src/components/ModDirectory.vue
src/components/ProfileSelection.vue
src/components/StartupChecks.vue

fix: re-render profiles on mod directory change

---

src/background.ts
src/components/AutoUpdate.vue
src/enums/IPCEvents.ts
src/main/logger.ts

feat: show download progress and prevent user from double clicking

---

src/components/TheFooter.vue

feat: link footer to patreon page

---

src/main/enb.ts
src/main/errorHandler.ts
src/main/gameFiles.ts
src/main/ipcHandler.ts
src/main/modOrganizer.ts

feat: copy game folder files on game launch

---

src/components/AutoUpdate.vue

feat: auto-update without needing user action

---

src/components/TheTitleBar.vue

fix: fix minimize button

---

src/components/AppFileSelect.vue
src/components/ModDirectory.vue
src/components/SkyrimDirectory.vue
src/components/TheStartupChecks.vue
src/views/ViewSettings.vue

fix: prevent showing the open button with startup checks

---

src/components/NavigationItem.vue
src/components/Resources.vue
src/components/TheNavigation.vue

feat: add link to GitHub

---

src/components/AppFileSelect.vue

feat: prevent the user from clicking if file dialog is open

---

package-lock.json
package.json
src/main/ipcHandler.ts
src/main/modOrganizer.ts

fix: prevent user from opening multiple MO2 instances

---

src/main/modOrganizer.ts

fix: if no enb has been selected, just copy the first one

---

src/assets/scss/settings/colours.scss
src/components/NavigationItem.vue

feat: change brand colours to match wildlander website

---

package-lock.json
package.json
src/components/BaseDropdown.vue
src/components/ENB.vue
src/components/Resolution.vue
src/components/TheNavigation.vue
src/main.ts
src/views/ViewGraphics.vue

- Close dropdowns when user clicks outside of the dropdown

feat: move resolution dropdown into navigation

---

src/main/graphics.ts

fix: ensure filepath to SSEDisplayTweaks uses the mod name

---

src/components/News.vue

style: remove news tag on every post

---

src/components/TheStartupChecks.vue
src/components/TheTitleBar.vue

fix: ensure close button is clickable on startup

---

src/assets/scss/settings/sizes.scss
src/components/AppPage.vue
src/components/TheHeader.vue
src/components/TheTitleBar.vue

style: remove excess space at the top of the logo

---

src/components/ProfileSelection.vue
src/components/Resolution.vue
src/main/ENB.ts
src/main/config.ts
src/main/modOrganizer.ts

feat: prevent showing the MO2 GUI when launching game

---

src/App.vue
src/background.ts
src/components/Community.vue
src/components/ENB.vue
src/components/ModDirectory.vue
src/components/ProfileSelection.vue
src/components/TheFooter.vue
src/components/TheHeader.vue
src/components/TheStartupChecks.vue
src/main/ENB.ts
src/main/config.ts
src/main/ipcHandler.ts
src/main/modOrganizer.ts
src/typings/modpack-metadata.d.ts

feat: allow naming ENBs with a namesENB.json

---

src/main/ENB.ts
src/main/config.ts
src/main/modOrganizer.ts

feat: backup ENB files before launching MO2/game

---

vue.config.js

chore: remove data on uninstall

---

src/main/autoUpdate.ts

chore: only auto update if device is connected

---

src/renderer/components/BaseDropdown.vue

fix: prevent dropdowns from overlapping icons

---

package.json
src/main.ts
src/main/controllers/wabbajack/wabbajack.controller.ts
src/main/services/config.service.ts
src/main/services/enb.service.ts
src/main/services/error.service.ts
src/main/services/modOrganizer.service.ts
src/main/services/modpack.service.ts
src/main/services/startup.service.ts
src/main/services/wabbajack.service.ts
src/main/services/window.service.ts
src/renderer/components/AppDropdownFileSelect.vue
src/renderer/components/BaseDropdown.vue
src/renderer/components/ProfileSelection.vue
src/renderer/components/Resolution.vue

fix: prevent invalid enbs from being persisted on mod selection

---

src/main/services/config.service.ts
src/main/services/game.service.ts
src/main/services/modOrganizer.service.ts

feat: copy skyrim launch logs after game launch

---

src/renderer/views/ViewAdvanced.vue

feat: add an information message when MO2 is running

---

src/main/services/modpack.service.ts
src/main/services/resolution.service.ts
src/renderer/components/Resolution.vue

feat: set resolution when it is selected, not on game start

---

package-lock.json
src/additional-instructions.json
src/main/controllers/modpack/modpack.controller.ts
src/main/controllers/resolution/resolution.controller.ts
src/main/services/enb.service.ts
src/main/services/instruction.service.ts
src/main/services/launcher.service.ts
src/main/services/modOrganizer.service.ts
src/main/services/modpack.service.ts
src/main/services/resolution.service.ts
src/main/services/startup.service.ts
src/main/services/system.service.ts
src/main/services/wabbajack.service.ts
src/renderer/components/Resolution.vue
src/types/additional-instructions.d.ts

feat: ultra-widescreen mods

---

src/main/services/startup.service.ts

chore: add extra logging on startup

---

src/renderer/App.vue
src/renderer/components/TheTitleBar.vue

fix: enable close and minimise buttons when modal is open

---

src/main/controllers/update/update.events.ts
src/main/services/update.service.ts
src/renderer/components/News.vue
src/renderer/components/Patrons.vue

fix: prevent a failed update from preventing use of the launcher

---

package-lock.json
package.json
src/main/services/system.service.ts
src/types/fetch-installed-software.d.ts

feat: massively decrease time to check for prerequisites

---

src/renderer/components/News.vue
src/renderer/services/cache.service.ts
src/renderer/services/patreon.service.ts
src/renderer/services/posts.service.ts

 chore: cache news and only update when there are changes

---

src/renderer/components/TheNavigation.vue

feat: display version number on game launch modal

---

src/main/services/error.service.ts
src/main/services/launcher.service.ts

fix: promt user to restart as admin if they get a permission error

---

src/assets/scss/utility.scss
src/renderer/App.vue
src/renderer/components/BaseButton.vue
src/renderer/components/BaseDropdown.vue
src/renderer/components/BaseMarquee.vue
src/renderer/components/LauncherVersion.vue
src/renderer/components/MO2RunningModal.vue
src/renderer/components/TheFooter.vue
src/renderer/components/TheNavigation.vue
src/renderer/views/AutoUpdate.vue
src/renderer/views/ViewAdvanced.vue

chore: remove global <p> styles

---

README.md
src/__tests__/unit/services/graphics.service.test.ts
src/__tests__/unit/services/modOrganizer.service.test.ts
src/main/services/graphics.service.ts
src/main/services/modOrganizer.service.ts

fix: prevent changes to graphics files being lost on restart
